### ISSUE TITLE
Loop Unrolling and Scalar Replacement (Register-level Tiling) 

### ISSUE THREAD

**Issue by Theoo1997** [bondhugula/pluto#100]
Hi, 
I was wondering the "unrolljam + ufactor" flag will apply Register-level Tiling in a specific loop/loops ? If yes how can I determine the exact loop/loops to apply RB? Also this transformation can be applied in manually-vectorized code?

**Comment by bondhugula** [comment]
Pluto automatically determines which loops to register tile -- it'll be one or more of the non-innermost loops inside of the innermost intra-tile band. Please see the matmul example for reference. Reg. manually vectorized code; it depends on how you vectorized it -- the input should be parseable by the polyhedral frontend we have. There are also other ways to encapsulate the inner body to potentially get pluto to register tile -- but it depends on whether it detects tilability. Pluto isn't meant to be a semi-automatic tool to apply transformations in a user-directed manner.

**Comment by Theoo1997** [comment]
Thanks a lot !!
