### ISSUE TITLE
pollycc reports syntax errors due to local variables

### ISSUE THREAD

**Issue by lahwaacz** [bondhugula/pluto#19]
When I mark the code of interest like this:
```c
void mat_mul0(int n_a_rows, int n_a_cols, const float *a, int n_b_cols, const float *b, float *m)
{
    int i, j, k;
#pragma scop
    for (i = 0; i < n_a_rows; ++i) {
        for (j = 0; j < n_b_cols; ++j) {
            float t = 0.0;
            for (k = 0; k < n_a_cols; ++k)
                t += a[i*n_a_rows+k] * b[k*n_a_cols+j];
            m[i*n_a_rows+j] = t;
        }
    }
#pragma endscop
}
```
and run `polycc matmul.c --tile --parallel -o matmul`, all I get is a syntax error:
```
[Clan] Error: syntax error at line 129, column 8.
Error extracting polyhedra from source file: 'matmul.c'
```
The line 129 corresponds to `float t = 0.0;`.

**Comment by bondhugula** [comment]
The Clan frontend can't parse the declaration inside. You can use the Pet frontend (--pet) to deal with it.  However, you'll run into another issue with the accesses (i*n_a_rows+k and others will be seen as non-affine ones) since there's no dimension lifting / delinearization support. So you'll have to use 2-d arrays if you want the dependence analysis here to work (i.e., m[i][j] += a[i][k]*b[k][j]).

**Comment by lahwaacz** [comment]
```
$ polycc --pet --tile --parallel matmul.c -o matmul
/stuff/pluto/src/pluto: unrecognized option '--pet'
```

**Comment by bondhugula** [comment]
The --pet option is only available in the 'pet' branch of the git. (You'll also need LLVM/Clang 3.4 for this). In any case, if it's rewritten in a way such that those accesses become affine, you'll be able to run it even without --pet.

**Comment by lahwaacz** [comment]
Then why are things [like this](https://github.com/bondhugula/pluto/blob/master/tuner/pltuner#L9) in the master branch?

**Comment by bondhugula** [comment]
Thanks for reporting - fixed.

**Comment by lahwaacz** [comment]
There are a couple more of those: https://github.com/bondhugula/pluto/search?utf8=%E2%9C%93&q=--pet&type=

**Comment by bondhugula** [comment]
Including benchmarks that needed --pet in the master branch was an oversight as well. Dropped now. Thanks.
