### ISSUE TITLE
pluto generated 2mm kernel does not compile  

### ISSUE THREAD

**Issue by ajaypanyala** [bondhugula/pluto#23]
I have Pluto built using the master branch.

polycc --tile --l2tile --intratileopt --unroll 2mm.c
generates a `2mm.pluto.c` that does not compile due to missing closing braces.

The attached 2mm.c is from Polybench-4.2
[2mm.zip](https://github.com/bondhugula/pluto/files/1965555/2mm.zip)

**Comment by bondhugula** [comment]
With the current master branch, I'm unable to reproduce this. Please reopen if this is still an issue.
