### ISSUE TITLE
Pluto MPI build fail

### ISSUE THREAD

**Issue by eraklon** [bondhugula/pluto#26]
Followed the instructions and I got the following error when I run make (relevant part of the output):

  _CC       pet_codegen-pet_codegen.o
  CCLD     pet_codegen
  CXX      dummy.o
  CC       pet_check_code-pet_check_code.o
  CXXLD    pet_check_code
/usr/bin/x86_64-linux-gnu-ld: pet_check_code-pet_check_code.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:889: recipe for target 'pet_check_code' failed
make[4]: *** [pet_check_code] Error 1
make[4]: Leaving directory '/work/pluto-distmem/pluto/pet'
Makefile:1085: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/work/pluto-distmem/pluto/pet'_

I tried to fix this by adding -fPIC to CCFLAGS, then I got this different error:

  _CXX      dummy.o
  CC       pet_check_code-pet_check_code.o
  CXX      scan.lo
  CXXLD    libpet.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     pet_codegen
  CXXLD    pet_check_code
./.libs/libpet.so: undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
./.libs/libpet.so: undefined reference to `llvm::sys::getDefaultTargetTriple[abi:cxx11]()'
./.libs/libpet.so: undefined reference to `clang::getClangFullVersion[abi:cxx11]()'
./.libs/libpet.so: undefined reference to `clang::DeclarationNameInfo::getAsString[abi:cxx11]() const'
./.libs/libpet.so: undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::Type const*, clang::Qualifiers)'
collect2: error: ld returned 1 exit status
Makefile:889: recipe for target 'pet_check_code' failed
make[4]: *** [pet_check_code] Error 1
make[4]: Leaving directory '/work/pluto-distmem/pluto/pet'
Makefile:1085: recipe for target 'all-recursive' failed_

llvm-config and clang both 3.4 version (but its a prebuilt one I got error when i try to build it from tarball),  gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5. Ubuntu 18.04.
Try to find the soulution and what I found it is a linker error which might be caused by compiling libraries with different version of gcc, but still dont know how to resolve this.

(LLVM build output:

_[ 94%] Building CXX object tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stacktrace_libcdep.cc.o
[ 94%] Building CXX object tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o
/opt/llvm/llvm/tools/compliler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc: In function ‘int __sanitizer::TracerThread(void*)’:
/opt/llvm/llvm/tools/compliler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:243:22: error: aggregate ‘sigaltstack handler_stack’ has incomplete type and cannot be defined
   struct sigaltstack handler_stack;
                      ^~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c99-extensions’
cc1plus: warning: unrecognized command line option ‘-Wno-gnu’
tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/build.make:158: recipe for target 'tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o' failed
make[2]: *** [tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/sanitizer_stoptheworld_linux_libcdep.cc.o] Error 1
CMakeFiles/Makefile2:18819: recipe for target 'tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/all' failed
make[1]: *** [tools/compliler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.x86_64.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2_
)

Got any idea what should I do?

**Comment by eraklon** [comment]
fixed llvm issue but still get the same error with pluto

**Comment by bondhugula** [comment]
It looks like pet is being compiled with the wrong version of Clang headers, or there is a mismatch between the version it was compiled against and the one it's being linked to. Could you post what flags you used with configure and the output of your 

llvm-config --version

and 

cat pet/config.log | grep llvm

**Comment by eraklon** [comment]
I can only do that tomorrow, because I had these errors the pc at my workplace.

Also i tried to install on my own laptop and got error even at configure time:

_checking clang/Basic/DiagnosticOptions.h usability... yes
checking clang/Basic/DiagnosticOptions.h presence... yes
checking for clang/Basic/DiagnosticOptions.h... yes
checking for clang/Lex/HeaderSearchOptions.h... yes
checking for clang/Lex/PreprocessorOptions.h... yes
checking for main in -lclangEdit... yes
configure: isl sources in /home/dszabo/pluto-distmem/pluto/isl
checking which isl to use... build
./configure: line 16688: syntax error near unexpected token `ISL,'
./configure: line 16688: `	PKG_CHECK_MODULES(ISL, isl)'
checking for pet/Makefile... no
configure: error: configure in pet/ failed_

I use no flags for ./configure.

llvm-config --version
_3.4svn_

cat pet/config.log | grep llvm
_configure:16112: checking for llvm-config
configure:16128: found /usr/local/bin/llvm-config
ac_cv_prog_llvm_config_found=yes
llvm_config_found='yes'_

Maybe I should make a different issue for this? I had this same configure error at my workplace too, but somehow it got resolved. Maybe because I also installed other versions of llvm/clang too or I dont know, but I think the problem lies here then. 

I downloaded clang and llvm tar from llvm website and built them with cmake, following these steps: [](https://llvm.org/docs/CMake.html)

**Comment by eraklon** [comment]
Ok so for my original problem (which is in the first comment)

I didn't used any configure flag.

llvm-config --version output:
3.4svn

cat pet/config.log | grep llvm output:
configure:16127: checking for llvm-config
configure:16143: found /usr/local/bin/llvm-config
ac_cv_prog_llvm_config_found=yes
llvm_config_found='yes'

Seems the same for me.

**Comment by eraklon** [comment]
I put -fPIC for CFLAGS and -shared to LDFLAGS for all subdiractories Makefile and now it installed and seems working.

**Comment by bondhugula** [comment]
> llvm-config --version output:
> 3.4svn

It looks like the version being compiled against isn't the version you downloaded and built. Did you build an SVN version or a stable one? If you downloaded and built clang and llvm from the released 3.4 version sources, that should definitely work. Did you install those in /usr/local/?

**Comment by bondhugula** [comment]
Pluto will now work with the latest version of Clang (version 3.4 is no longer needed); also, the pet branch has been merged into the master. Please reopen if you face this issue with the current master.
