### ISSUE TITLE
Pluto MPI heat-3d example error

### ISSUE THREAD

**Issue by eraklon** [bondhugula/pluto#28]
I got the following error when I run polycc with heat-3d:

_$ ../../polycc heat-3d.c --distmem --mpiomp --commopt_fop --tile  --isldep --lastwriter --cloogsh --timereport  -o heat-3d.distopt_fop.c
[pluto] Turning on lastwriter
[pluto] Assuming data arrays are declared globally; turn on variables_not_global (and include macro definitions) otherwise
[Clan] Error: syntax error at line 95, column 28.
Error extracting polyhedra from source file: 'heat-3d.c'_

heat-1d and heat-2d report similar error. (they both point to the modulo (%) operator)

**Comment by eraklon** [comment]
When i do with 'make distopt' it works (but that use the 'alt' version)

**Comment by bondhugula** [comment]
Yes, it's the alt version that is meant to work with the distmem targets. The vanilla 'heat-3d.c' version cannot be parsed via clan; it requires the 'pet'-based frontend for Pluto (--pet) and the scop resulting from it has expressions/forms that distributed memory code generation can't handle yet. So please use the alt version - it's the one that we've always used for experiments and in all the publications.

**Comment by bondhugula** [comment]
make dist_test in examples/heat-3d passes. heat-3d-alt.c is the one that is intended to be used for distributed memory codegen. Closing this.
