### ISSUE TITLE
Another build issue with pet branch 

### ISSUE THREAD

**Issue by zpmaths** [bondhugula/pluto#31]
Hi,
I met the following error when I compiled the pet branch: 
```
program.c: In function ‘pet_to_pluto_stmts’:
program.c:4556:18: error: ‘struct pet_stmt’ has no member named ‘stmt_text’
         if (pstmt->stmt_text) {
                 ^~
```

then I checked the definition of `struct pet_stmt` in `pet.h` 
```
struct pet_stmt {
        int line;
        isl_set *domain;
        isl_map *schedule;
        struct pet_expr *body;

        unsigned n_arg;
        struct pet_expr **args;
};
```
and found  that `stmt_text` was not a member of `struct pet_stmt`
Does this problem caused by different versions of pet ? I have tried from `pet0.03` to `pet0.11`, and 
got the same error.

**Comment by bondhugula** [comment]
Sorry for the late response - had missed this. 

You missed running ./apply_patches.sh before building Pluto. (README and INSTALL document this).

**Comment by bondhugula** [comment]
Running ./apply_patches.sh is no longer needed with the current master.
