### ISSUE TITLE
Memory leaks with DFP

### ISSUE THREAD

**Issue by bondhugula** [bondhugula/pluto#43]
$ valgrind --leak-check=full ./src/pluto test/gemver.c --dfp --hybridfuse --notile --noparallel 

[pluto] Auto-transformation time: 0.525126s
[pluto] 		Total FCG Construction Time: 0.262769s
[pluto] 		Total FCG Colouring Time: 0.052208s
[pluto] 		Total Scaling + Shifting time: 0.040810s
[pluto] 		Total Skewing time: 0.046699s
[pluto] 		Total constraint solving time (LP/MIP/ILP) time: 0.267857s
[pluto] Code generation time: 0.418973s
[pluto] Other/Misc time: 1.653294s
[pluto] Total time: 2.733726s
[pluto] All times: 0.136333 0.525126 0.418973 1.653294
==25470== 
==25470== HEAP SUMMARY:
==25470==     in use at exit: 106,495 bytes in 52 blocks
==25470==   total heap usage: 200,042 allocs, 199,990 frees, 28,838,540 bytes allocated
==25470== 
==25470== 64 bytes in 4 blocks are definitely lost in loss record 40 of 49
==25470==    at 0x483880B: malloc (vg_replace_malloc.c:309)
==25470==    by 0x42716D: dims_to_be_skewed (in /home/uday/git/pluto/src/pluto)
==25470==    by 0x42797A: introduce_skew (in /home/uday/git/pluto/src/pluto)
==25470==    by 0x43AAF8: pluto_auto_transform (in /home/uday/git/pluto/src/pluto)
==25470==    by 0x42C2B5: main (in /home/uday/git/pluto/src/pluto)
==25470== 
==25470== LEAK SUMMARY:
==25470==    definitely lost: 64 bytes in 4 blocks
==25470==    indirectly lost: 0 bytes in 0 blocks
==25470==      possibly lost: 0 bytes in 0 blocks
==25470==    still reachable: 106,431 bytes in 48 blocks
==25470==         suppressed: 0 bytes in 0 blocks
==25470== Reachable blocks (those to which a pointer was found) are not shown.
==25470== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==25470== 
==25470== For counts of detected and suppressed errors, rerun with: -v

**Comment by aravind343** [comment]
Issue fixed in commit https://github.com/bondhugula/pluto/commit/370a8361e642f4be9aacd94016ca26db4782a6a3
