### ISSUE TITLE
DFP based typed fusion leads to loss of parallelism

### ISSUE THREAD

**Issue by bondhugula** [bondhugula/pluto#55]
Reproduce on the pluto-rlp branch with:

$ ./polycc test/multi-stmt-stencil-seq.c --typedfuse

**Comment by aravind343** [comment]
Typed fuse is enabled only with the dfp framework.  Hence --dfp flag has to be included in the command line. Here is the output with the flag --dfp included in the command line.

`$ ./polycc test/multi-stmt-stencil-seq.c --dfp --typedfuse`

T(S1): (0, 0, 0, 0, i)
loop types (scalar, scalar, scalar, scalar, loop)

T(S2): (1, 0, 0, 0, i)
loop types (scalar, scalar, scalar, scalar, loop)

T(S3): (1, 1, 0, 0, i)
loop types (scalar, scalar, scalar, scalar, loop)

T(S4): (1, 1, 1, 0, i)
loop types (scalar, scalar, scalar, scalar, loop)

T(S5): (1, 1, 1, 1, i)
loop types (scalar, scalar, scalar, scalar, loop)

**Comment by bondhugula** [comment]
If --typedfuse is a choice under DFP alone, we should turn on DFP whenever --typedfuse is provided.

**Comment by bondhugula** [comment]
And similarly for --hybridfuse and any other fusion heuristics under DFP.

**Comment by aravind343** [comment]
Fixed in commit 12d8030c03b5e8cefc6ac345b1ffa4cadcb5ba90. In case, an LP solver like glpk or gurobi is not enabled during configure, then typedfuse (or hybridfuse) is disabled and then uses the original ILP based Pluto algorithm.
