### ISSUE TITLE
test_libpluto fails on the master branch

### ISSUE THREAD

**Issue by bondhugula** [bondhugula/pluto#57]
Running ./test_libpluto yields on current master tip: 6118e7f7aa488bc8df9067e497a8287fc8075758

...
*** TEST CASE 6

[Pluto] Number of statements: 1
[Pluto] Total number of loops: 3
[Pluto] Number of deps: 1
[Pluto] Maximum domain dimensionality: 3
[Pluto] Number of parameters: 2
[pluto] Diamond tiling not possible/useful
[Pluto] Affine transformations [<iter coeff's> <const>]

T(S1): (i0, i1+i2, i1)
loop types (loop, loop, loop)

[Pluto] After tiling:
T(S1): (i0/32, (i1+i2)/32, i1/32, i0, i1+i2, i1)
loop types (loop, loop, loop, loop, loop, loop)

[pluto_mark_parallel] 1 parallel loops
t1 {loop with stmts: S1, }

[R, T] -> { S_0[i0, i1, i2] -> [o0, o1, o2, i0, i1 + i2, i1] : -31 + i0 <= 32o0 <= i0 and -31 + i1 + i2 <= 32o1 <= i1 + i2 and -31 + i1 <= 32o2 <= i1 }
[Pluto] Number of statements: 1
[Pluto] Total number of loops: 3
[Pluto] Number of deps: 1
[Pluto] Maximum domain dimensionality: 3
[Pluto] Number of parameters: 2
[pluto] Diamond tiling not possible/useful
[Pluto] Affine transformations [<iter coeff's> <const>]

T(S1): (i0, i1+i2, i1)
loop types (loop, loop, loop)

[Pluto] After tiling:
T(S1): (i0/32, (i1+i2)/32, i1/32, i0, i1+i2, i1)
loop types (loop, loop, loop, loop, loop, loop)

[pluto_mark_parallel] 1 parallel loops
t1 {loop with stmts: S1, }

*** TEST CASE test_lib_pluto_schedule ***

lt-test_libpluto: program.cpp:1997: isl_stat basic_map_extract_dep(isl_basic_map*, void*): Assertion `0' failed.
Aborted (core dumped)

**Comment by aravind343** [comment]
A clean rebuild should fix this issue.

**Comment by bondhugula** [comment]
Confirmed a clean rebuild fixes the issue.
