### ISSUE TITLE
Improve intra-tile locality optimization

### ISSUE THREAD

**Issue by bondhugula** [bondhugula/pluto#59]

**Comment by aravind343** [comment]
Test case which exposes missed opportunity in intra-tile optimizations is added in commit a4bd9bbdb2ede638d648d73a59fcbb02a244248b

**Comment by aravind343** [comment]
Expected transformation for test/intratileopt6.c found (commit id 46bcc5f476d437abe08c1367ecd63db7f8d27485). For 2mm and 3mm in polybench suite, Pluto should be able to find a transformation with better spatial locality (and vectorizable loop at innermost level).

**Comment by aravind343** [comment]
`test/intratileopt6.c` with `--typedfuse`  segfaults.

**Comment by aravind343** [comment]
Fixed in commit https://github.com/bondhugula/pluto/commit/94bd2897b0227a7b7be70361b3045d79a2e67377

**Comment by bondhugula** [comment]
I see the following errors on a make test.

```
./test/intratileopt5.c with --maxfuse              error: no check strings found with prefix 'CHECK-TILE:'
[Failed]  ./test/intratileopt5.c!
./test/intratileopt5.c with --maxfuse --notile     error: no check strings found with prefix 'CHECK-NOTILE:'
[Failed]  ./test/intratileopt5.c!
```

**Comment by bondhugula** [comment]
Looks like I had an outdated test script - this works fine now after a reconfigured build.
