### ISSUE TITLE
Build issue with PET branch

### ISSUE THREAD

**Issue by SumedhArani** [bondhugula/pluto#6]
This error throws up on,
```./configure```

The last few lines of the error message is as follows-
```checking which clang to use... system
checking for llvm-config... yes
checking clang/Basic/SourceLocation.h usability... no
checking clang/Basic/SourceLocation.h presence... no
checking for clang/Basic/SourceLocation.h... no
configure: error: clang header file not found
checking for pet/Makefile... no
configure: error: configure in pet/ failed
```

This is in the case of Ubuntu 16.04 LTS and clang version 3.8 and LLVM version 3.8.
The master branch works clean.

Cheers.

**Comment by bondhugula** [comment]
Please refer to the README. You need clang-3.4 - it won't work with higher versions.

**Comment by mankey101** [comment]
I am facing the same issue while using clang 10.0.0. Do I still need to use clang3.4 or is the repo updated to work with future clang versions?

**Comment by bondhugula** [comment]
It has been updated to work with up until clang 8.0. pet/README has this information. It's also now possible to just integrate pet from upstream. So whatever the most recent version of pet supports can be easily supported.

**Comment by bondhugula** [comment]
Correction: anything up until clang 9.0 should work.

**Comment by bondhugula** [comment]
Also, the pet branch has been merged into the master and is now no longer maintained. Please just use the master.

**Comment by mankey101** [comment]
I'm using clang-8.0.1 and get the same PET config error.

**Comment by bondhugula** [comment]
> I'm using clang-8.0.1 and get the same PET config error.

Please post the errors from pet/config.log. Just stating that you encounter that error gives us no information! There are multiple very different reasons why one could end up with that, but it's often due to an incomplete set of clang includes.

In any case, given the title of this issue, this was all originally about the pet branch which is now obsolete. Please post a fresh issue if you see this on the master branch.

**Comment by mankey101** [comment]
I had the exact same issue which is why I didn't explicitly state the config.log. But if it helps here it is: 
[config.log](https://github.com/bondhugula/pluto/files/4160626/config.log)

**Comment by bondhugula** [comment]
> I had the exact same issue which is why I didn't explicitly state the config.log. But if it helps here it is:
> [config.log](https://github.com/bondhugula/pluto/files/4160626/config.log)

We need to look at pet/config.log and not the config.log at the top level. (I think you linked to the latter.)

**Comment by dpotop** [comment]
I have the same issue with the development branch. Here is pet/config.log . 
[config.log](https://github.com/bondhugula/pluto/files/4239121/config.log)

**Comment by bondhugula** [comment]
The pet branch is obsolete and I'm thus closing this issue.

**Comment by gschwaer** [comment]
For future reference (also for myself, since I ended up here twice already):
If you are on Ubuntu you need to additionally install the `libclang-X.X-dev` package.
E. g. I had the following packages installed:
```
libclang-common-6.0-dev/bionic,now 1:6.0-1ubuntu2 amd64 [installed,automatic]
  clang library - Common development package
libclang1-6.0/bionic,now 1:6.0-1ubuntu2 amd64 [installed,automatic]
  C interface to the clang library
```
Missing was this package (which contains the header files):
```
libclang-6.0-dev/bionic,now 1:6.0-1ubuntu2 amd64
  clang library - Development package
```

**Comment by makslevental** [comment]
here's the magic combination of flags and env variables if you're llvm build dir is different from where headers are kept

```
CPATH=/home/mlevental/dev_projects/phism/polygeist/llvm-project/clang/include ./configure --with-clang-prefix=/home/mlevental/dev_projects/phism/polygeist/llvm-project/build
```
