### ISSUE TITLE
Configuration fails on PET

### ISSUE THREAD

**Issue by dpotop** [bondhugula/pluto#72]
Yet another attempt to compile Pluto. This time on fedora. The environment seems saner than on MacOSX and Ubuntu (for instance, FileCheck is part of llvm-devel). However, the configuration process fails on pet, after a few issues I was able to work around.

The issues:
- I had to manually configure, compile, and install openscop and clan. The top-level configure process does not do it correctly.
- I also had to do it on pet, but there it fails. Here is pet/config.log:
[config.log](https://github.com/bondhugula/pluto/files/4239316/config.log)

It seems that the pet configuration process is looking for a file called clang/Basic/SourceLocation.h that does not exist in clang-9.0.0

**Comment by bondhugula** [comment]
But clang/Basic/SourceLocation.h has always been part of clang. 
https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/SourceLocation.h 

It looks like you don't have all the development files necessary installed. How did you install the clang headers and libraries? (from sources?)

What issue did you run into with openscop?

**Comment by dpotop** [comment]
Ok, I had forgot to install clang-devel (I had only installed llvm clang, and llvm-devel).
Installing clang-devel solved a lot of configuration problems. Now, configuration runs
smoothly, but compilation blocks on pet.

Here are:
- The output of autogen.sh (and previous commands)
     [autogen.txt](https://github.com/bondhugula/pluto/files/4239518/autogen.txt)

- The top-level config.log
     [config.log](https://github.com/bondhugula/pluto/files/4239520/config.log)

- The output of the compilation process
     [compil.txt](https://github.com/bondhugula/pluto/files/4239522/compil.txt)

The version for all LLVM/CLANG packages is 9.0.0 (Fedora 9.0.0-1.fc31).

**Comment by bondhugula** [comment]
You may want to just get pet working separately first. The best place to post that would be on isl-development@googlegroups.com - for a faster response. (isl-dev is for both pet and isl issues.) The version of pet included in pluto should work with llvm/clang 9.0.0. Make sure your pet submodule is up to date.

**Comment by dpotop** [comment]
Just to be sure that I understand correctly:
1. I did not obtain pet separately. I simply called "git submodule init" and "git submodule update" inside pluto prior to calling autoconf.sh. Can I assume I have the last version?
2. Should I try to reconfigure and compile pet separately, or just post the whole problem there?

**Comment by bondhugula** [comment]
Yes, that's right - you could just switch to the pet directory in pluto, and try with:

$ ./configure <whatever options>
$ make

Reproduce the issue, and post it on isl-dev with the pet version (git describe in the pet dir will provide you that - it should be pet-0.11.3-5-g2911db3.

**Comment by dpotop** [comment]
That's weird. Calling "git describe" in the pet folder gives:

> fatal: No names found, cannot describe anything.

And yet, I did nothing to put pet there.
The same is true for the following sub-folders: candl, isl, pet, piplib, 
but not for: clan, cloog, openscop, orio.
Folder polylib gives a different message (is it part of pluto?).

Maybe this is the problem.

**Comment by bondhugula** [comment]
Which pet commit are you at in that directory? (git show)

**Comment by bondhugula** [comment]
Could you please pull again and update your pet submodule? (There was an inadvertent update to the pet submodule a couple of days back, which I just fixed now.)
$ git pull
$ git submodule update pet

**Comment by dpotop** [comment]
Yes! It compiles. Thank you.

**Comment by bondhugula** [comment]
Thank you for your patience and persistence here!
