### ISSUE TITLE
Compilation error and solution

### ISSUE THREAD

**Issue by dpotop** [bondhugula/pluto#75]
On MacOS 10.15.3 with llvm/clang 9.0, the compilation of the toolchain fails on JitRunner.cpp.
The solution to make it compile is to add to this file :
 

`#include <sstream>`

**Comment by bondhugula** [comment]
I'm sorry I didn't understand. JitRunner.cpp is part of mlir - did you mean to post elsewhere?

**Comment by dpotop** [comment]
Well, the compilation of https://github.com/bondhugula/llvm-project.git fails. It may be that JitRunner.cpp is not modified from https://github.com/llvm/llvm-project.git, but I noted this here. Sorry if this is not helpful.

**Comment by bondhugula** [comment]
For the pluto build itself, you don't need to use https://github.com/bondhugula/llvm-project.git - instead, any LLVM/Clang version from upstream supported by the pet submodule should work (up until llvm/clang 9.0.0).

**Comment by dpotop** [comment]
My bad. I intended to submit this to your MLIR fork, but I got confused.

Le dim. 22 mars 2020 à 00:49, Uday Bondhugula <notifications@github.com> a
écrit :
