### ISSUE TITLE
build candl error happend when make

### ISSUE THREAD

**Issue by yhj050806** [bondhugula/pluto#79]
I follow the below flow to build pluto
$ git clone https://github.com/bondhugula/pluto.git
$ cd pluto/
$ git submodule init
$ git submodule update
$ ./autogen.sh
$ ./configure --enable-debug
$ make -j4

but error happened when build candl。[ gcc (Debian 6.3.0-18+deb9u1)]

make[4]: Leaving directory '/data00/home//work/study/pluto/clan/tests'
make[3]: Leaving directory '/data00/home//work/study/pluto/clan'
make[2]: Leaving directory '/data00/home//work/study/pluto/clan'
Making all in candl
make[2]: Entering directory '/data00/home//work/study/pluto/candl'
**make[2]: *** No rule to make target 'all'.  Stop.**
make[2]: Leaving directory '/data00/home//work/study/pluto/candl'
Makefile:521: recipe for target 'all-recursive' failed
**make[1]: *** [all-recursive] Error 1**
make[1]: Leaving directory '/data00/home//work/study/pluto'
Makefile:391: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YangWang92** [comment]
You may need to install textinfo.

configure: error: Please install texinfo.
