### ISSUE TITLE
while using "make -j4", the process fails. 

### ISSUE THREAD

**Issue by ShikharJain97** [bondhugula/pluto#90]
(base) shikharj@ShikharJ:~/pluto$ make -j4
make  all-recursive
make[1]: Entering directory '/home/shikharj/pluto'
Making all in piplib
make[2]: Entering directory '/home/shikharj/pluto/piplib'
Making all in .
make[3]: Entering directory '/home/shikharj/pluto/piplib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/shikharj/pluto/piplib'
Making all in example
make[3]: Entering directory '/home/shikharj/pluto/piplib/example'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/shikharj/pluto/piplib/example'
Making all in doc
make[3]: Entering directory '/home/shikharj/pluto/piplib/doc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/shikharj/pluto/piplib/doc'
Making all in test
make[3]: Entering directory '/home/shikharj/pluto/piplib/test'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/shikharj/pluto/piplib/test'
make[2]: Leaving directory '/home/shikharj/pluto/piplib'
Making all in polylib
make[2]: Entering directory '/home/shikharj/pluto/polylib'
make  all-recursive
make[3]: Entering directory '/home/shikharj/pluto/polylib'
Making all in include
make[4]: Entering directory '/home/shikharj/pluto/polylib/include'
Making all in polylib
make[5]: Entering directory '/home/shikharj/pluto/polylib/include/polylib'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/include/polylib'
make[5]: Entering directory '/home/shikharj/pluto/polylib/include'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/include'
make[4]: Leaving directory '/home/shikharj/pluto/polylib/include'
Making all in Test
make[4]: Entering directory '/home/shikharj/pluto/polylib/Test'
Making all in Zpolytest
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/Zpolytest'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/Zpolytest'
Making all in ehrhart
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/ehrhart'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/ehrhart'
Making all in ehrhart_union
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/ehrhart_union'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/ehrhart_union'
Making all in ranking
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/ranking'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/ranking'
Making all in general
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/general'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/general'
Making all in pp
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test/pp'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test/pp'
make[5]: Entering directory '/home/shikharj/pluto/polylib/Test'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/shikharj/pluto/polylib/Test'
make[4]: Leaving directory '/home/shikharj/pluto/polylib/Test'
make[4]: Entering directory '/home/shikharj/pluto/polylib'
make[4]: Leaving directory '/home/shikharj/pluto/polylib'
make[3]: Leaving directory '/home/shikharj/pluto/polylib'
make[2]: Leaving directory '/home/shikharj/pluto/polylib'
Making all in isl
make[2]: Entering directory '/home/shikharj/pluto/isl'
make  all-recursive
make[3]: Entering directory '/home/shikharj/pluto/isl'
Making all in .
make[4]: Entering directory '/home/shikharj/pluto/isl'
make[4]: Leaving directory '/home/shikharj/pluto/isl'
Making all in doc
make[4]: Entering directory '/home/shikharj/pluto/isl/doc'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/shikharj/pluto/isl/doc'
make[3]: Leaving directory '/home/shikharj/pluto/isl'
make[2]: Leaving directory '/home/shikharj/pluto/isl'
Making all in openscop
make[2]: Entering directory '/home/shikharj/pluto/openscop'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/shikharj/pluto/openscop'
Making all in cloog-isl
make[2]: Entering directory '/home/shikharj/pluto/cloog-isl'
Making all in .
make[3]: Entering directory '/home/shikharj/pluto/cloog-isl'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/shikharj/pluto/cloog-isl'
make[2]: Leaving directory '/home/shikharj/pluto/cloog-isl'
Making all in clan
make[2]: Entering directory '/home/shikharj/pluto/clan'
make  all-recursive
make[3]: Entering directory '/home/shikharj/pluto/clan'
Making all in .
make[4]: Entering directory '/home/shikharj/pluto/clan'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/shikharj/pluto/clan'
Making all in doc
make[4]: Entering directory '/home/shikharj/pluto/clan/doc'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/shikharj/pluto/clan/doc'
Making all in tests
make[4]: Entering directory '/home/shikharj/pluto/clan/tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/shikharj/pluto/clan/tests'
make[3]: Leaving directory '/home/shikharj/pluto/clan'
make[2]: Leaving directory '/home/shikharj/pluto/clan'
Making all in candl
make[2]: Entering directory '/home/shikharj/pluto/candl'
Making all in .
make[3]: Entering directory '/home/shikharj/pluto/candl'
  CC       source/candl-candl.o
  CC       source/libcandl_la-dependence.lo
  CC       source/libcandl_la-ddv.lo
  CC       source/libcandl_la-scop.lo
source/candl.c:38:10: fatal error: osl/scop.h: No such file or directory
   38 | #include <osl/scop.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:856: source/candl-candl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
source/ddv.c:45:10: fatal error: osl/statement.h: No such file or directory
   45 | #include <osl/statement.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
source/scop.c:43:10: fatal error: osl/scop.h: No such file or directory
   43 | #include <osl/scop.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:779: source/libcandl_la-ddv.lo] Error 1
make[3]: *** [Makefile:786: source/libcandl_la-scop.lo] Error 1
In file included from source/dependence.c:51:
./include/candl/piplib.h:40:11: fatal error: piplib/piplibMP.h: No such file or directory
   40 | # include <piplib/piplibMP.h>
      |           ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:772: source/libcandl_la-dependence.lo] Error 1
make[3]: Leaving directory '/home/shikharj/pluto/candl'
make[2]: *** [Makefile:907: all-recursive] Error 1
make[2]: Leaving directory '/home/shikharj/pluto/candl'
make[1]: *** [Makefile:519: all-recursive] Error 1
make[1]: Leaving directory '/home/shikharj/pluto'
make: *** [Makefile:389: all] Error 2

**Comment by bondhugula** [comment]
Did you check out all submodules successfully? Do you have a non-empty openscop directory at the top level? Similarly for piplib.

**Comment by zimgithub** [comment]
thanks for quick response.
The problem is resolved.
