### ISSUE TITLE
build failing for cloog-isl with error message: /usr/bin/texi2dvi: pdfetex exited with bad status, quitting. make[3]: *** [Makefile:2301: doc/cloog.pdf] Error 1

### ISSUE THREAD

**Issue by pal-stdr** [bondhugula/pluto#98]
Hello

I have faced exactly similar issue (posted [here](https://github.com/periscop/cloog/issues/51)) while I was trying to build [ClooG](https://github.com/periscop/cloog) separately. And found [a way around](https://github.com/periscop/cloog/issues/51#issuecomment-1693457174) which is not a solid fix.

Following is the error report
```
....
...
Output written on cloog.pdf (46 pages, 246768 bytes).
Transcript written on cloog.log.
/usr/bin/texi2dvi: pdfetex exited with bad status, quitting.
make[3]: *** [Makefile:2301: doc/cloog.pdf] Error 1
....
....
```

OS: Ubuntu 20.04
llvm: 16.0.6 (Locally build and set to the `$PATH`)

Any idea how to find a stable fix for that?

Thanks in advance!

**Comment by FC-Akhi** [comment]
Hello @phschaad 

I ran into the same issue. I am using `LLVM 16.0.6` and `Ubuntu 20.04`.

> Before installing them, please purge/clean if you have installed one/some of them before. `sudo apt-get install texinfo texlive texlive-latex-extra texlive-science`

The above technique worked for me. I also performed a purge/clean using the below commands:

*Note: Cleaning texlive only*
`sudo apt-get purge texlive*`

Check what it's removing before confirming with 'Y'. 🙂
`sudo apt-get autoremove`

`sudo apt-get remove tex-common --purge`

Check what it's removing before confirming with 'Y'. 🙂
`sudo apt-get autoremove`

Hope it helps you too.
